### ISSUE TITLE
LUA Errors in Retail version.

### ISSUE THREAD

**Issue by L30m4nc3r** [Talryn/CharacterNotes#12]
![image](https://user-images.githubusercontent.com/710285/233784544-57658ca0-5135-4bd4-b22a-4c401e8dd283.png)

**Comment by Talryn** [comment]
I could not reproduce the errors.  I assume the locale is enUS / English?

My test was with game client 10.0.7 and Character Notes 10.0.8.  I tried with no other addons enabled and also with BugSack and BugGrabber enabled.  I did not see any errors and the addon worked as expected.

You may want to re-install the addon.  Those errors occur when it cannot find the locale files and the entries in it.  I did check and the current release here on GitHub does have the right files with all the entries.
