### ISSUE TITLE
Request: allow new lines in notes

### ISSUE THREAD

**Issue by RabbleCode** [Talryn/CharacterNotes#18]
Nice-to-have feature request: ability to add new lines into note body. 

I like to tag my notes with a date, and it'd be nice to separate notes from different dates for the same person on different lines.

For example, something like this:

> 11/1/24 - Ran WC, cool tank
> 
> 11/5/24 - Ran SFK, great run!

**Comment by Talryn** [comment]
There is an option that would enable that.  In the settings look for "Multiline Notes".  Once enabled, the window to edit notes will not save if you hit the enter key but should enter a new line.  You will need to click the Save button to save a note.

Technically the app always supported new lines in notes but the enter to save functionality was initially there for convenience.

If you have any issues with it, let me know.

**Comment by RabbleCode** [comment]
Well damn, I'm embarrassed I missed that! Seems to be working exactly as I would like. Thank you! And thank you so much for supporting this addon, it's one of my favorites.
