### ISSUE TITLE
Willing to contribute / Locale files are incomplete.

### ISSUE THREAD

**Issue by Karzik** [Talryn/CharacterNotes#3]
I would like to contribute and add a "/setrating" option, but it appears the locale files in GitHub are missing all of the entries.

**Comment by Talryn** [comment]
Hi, you would like to add an option with a syntax like the following?

    /setrating <name> <rating>

I can add it or you can if you wish.  I guess that is missing.  There is a slash command to delete a rating but not set.

The localization is handled by the WoWAce / CurseForge site.  When the addon is packaged (whenever it is tagged), the packager gets the localizations and adds them to the package.

I'm not sure what localization string you wish to add, but using a localized string at least requires adding it to the English (enUS) section here:

https://www.wowace.com/projects/character-notes/localization

Click the English flag to see all the localized string.

You can even check if your strings are added by using the export feature.  It is under the Localization drop down.  It shows you the output you will get in the Locale files.

While developing, you can copy over the actual localization files from a packaged version of the addon and then make the changes there.  You can either just add the appropriate localized strings in the Locale files or you can export from WoWAce and replace the localized strings.

**Comment by Karzik** [comment]
Been programming for over 30 years, and this is my first LUA/Addon modification I'm making so I'm new to the Ace localization.  I'm just adding one message since I'm adding the SetRatingHandler code ("Set rating for %s: %d").

I'll make the change and push it up and will try to figure out adding the localization string as well.

**Comment by Karzik** [comment]
Keep getting a 403 error when attempting to push the branch up.  Tried all the solutions from Google but still getting the same thing.  Any thoughts?

remote: Permission to Talryn/CharacterNotes.git denied to karzik.
fatal: unable to access 'https://github.com/Talryn/CharacterNotes.git/': The requested URL returned error: 403

Tried switching to SSH as well.

**Comment by Talryn** [comment]
That trailing / on the URL doesn't look right.  I would remove it.

The link from the main page shows this URL for HTTPS:

https://github.com/Talryn/CharacterNotes.git

If you have any other questions, just let me know.

**Comment by Karzik** [comment]
That's what I have in the configuration also, looks like the GIT client is just appending that on the output.

I am able to push to my own repository, just not this one.  Are there any special permissions you have in place that would prevent people from pushing up branches/changes maybe?

**Comment by Talryn** [comment]
My mistake.  I didn't realize what you were trying to do and should have thought more about it.

The usual procedure is to fork the repository so you have your own copy, but GitHub will know it is linked to this one.  You make your changes and then on GitHub you can submit a Pull Request.  The owner of the repository then approves the PRs and they get merged into the main code base.

**Comment by Karzik** [comment]
Got it!  I’ll do that then thanks!

**Comment by Talryn** [comment]
No problem.  I wish I had thought of it earlier.

**Comment by Karzik** [comment]
No worries.  I'm always used to just creating a branch off of the main repository and doing it that way.

Submitted the pull request, looks like it went through properly also.  I wasn't exactly sure how to add the message into the master Locale; however, so until that message is added it will generate an error.
